/**
 * Created by kann on 03-12-2014.
 */
public class phrases {

    public static final String[] jokePhrases = {
            "Alle børnene drak øl. Undtaget Teis og Eske, de sniffede lightervæske.",
            "Alle børnene svømmede ind til stranden, undtagen Kaj - Han mødte en haj.",
            "Alle børnene udløste deres faldskærm, undtagen Hening - Han elskede spænding.",
            "Alle børnene hoppede over hundelorten, undtagen Saddam, han satte sig ned og sagde nam.",
            "Alle børnene sad i redningsflåden, undtagen Mads, for der var ikke plads.",
            "Alle børnene blev forkølet, undtagen Lars, han fik SARS",
            "Alle børnene tegnede torturofre, undtagen Keld, han stod model. ",
            "Alle børnene bankede tæpper, undtagen Hektor, han bankede rektor.",
            "Alle børnene stormede B, undtagen Vang han døde på lang",
            "Alle børnene stod bagest i toget og grinede. Undtagen Jesper. Han var spændt efter.",
            "Alle børnene holdt fingrene fra mortorsaven. Undtagen Stig. Han blev kun 10.",
            "Alle børnene spillede dart. Undtagen Søren. Han hang fast på døren.",
            "Alle børnene øvede sig i at dykke. Undtagen Bente. Det var hende de skulle hente.",
            "Alle børnene kiggede ned i gylletanken. Undtagen Frede. Han blev dernede.",
            "Alle børnene kunne lide truede dyr. Undtagen Amanda. Hun skød en panda.",
            "Alle på Christiania festede. især Mads - han røg hash!",
            "Alle børnene kastede med håndgranater. Undtagen Bob. Han samlede dem op",
            "Alle børnene gik på jagt, undtagen Jytte, hun var bytte. ",
            "Alle børnene gik over kløften, undtagen Bo, han var bro.",
            "Alle børnene gik ind i skoven med motorsaven, undtagen Helle, det var hende, de skulle fælde",
            "Alle børnene græd i kirken, undtagen Stig, han var lig. ",
            "Alle børnene stoppede ved skrænten, undtagen Finn, han var blind.",
            "Alle børnene brugte køller, undtagen Bo, det var ham de slog.",
            "Alle børnene røg smøger, undtagen Rose, hun havde tuberkulose.",
            "Alle drengene gik med læderjakker, undtagen Ole, han gik med kjole.",
            "Alle børnene gik til tandlægen, undtagen Therese, hun havde protese.",
            "Alle børnene vinkede farvel til terroristerne, undtagen Sidsel, hun var gidsel.",
            "Alle børnene kom hjem fra jagten, undtagen Karen, hun blev forvekslet med haren.",
            "Alle pigerne var ludere, Undtagen Irma, Det var hendes firma",
            "Alle børnene slog søm I korset, Undtagen Elias, Han var Messias",
            "Alle børnene gav duerne brød, Undtagen Mick, Han gav dem arsenik.",
            "Alle børnene overlevede besøget på kassernen. Undtagen Ruth, hun blev skudt.",
            "Alle børnene heppede på Sten. Undtagen Frank, det var ham der fik bank.",
            "Alle børnene gravede huller. Undtagen Poul, han var skovl.",
            "Alle pigerne fik sperm I munden. Undtagen Lis, hun fik tis. ",
            "Alle børnene blev slæbt efter bilen. Undtagen Mads, han gav den gas.",
            "Alle børnene kom sikker igennem minifeltet. Undtagen Thøger, ham brugte de som søger.",
            "Alle børnene brugte wc-papir. undtagen Morten, han brugte skjorten.",
            "Alle børnene havde fingrene I skruestikken, Undtagen Bente, hun spændte",
            "Alle børnene beskyttede sig mod AIDS, Undtagen Frede, Han havde det allerede",
            "Alle børnene løb væk fra kanibalerne, Undtagen Morten og Arne, De blev lavet om til chili con carne",
            "Alle børnene fik sne i hovedet, undtagen Lise, hun fik en flise.",
            "Alle børnene legede med motorsav, undtagen Stoffer, han var offer.",
            "Alle børnene jagtede piger, undtagen Hans, han var svans. ",
            "Alle børnene gik glade gennem svingdøren, undtagen Mikkel, han fik mast en testikel.",
            "Alle børnene brækkede sig, undtagen Bob, han slikkede det op!",
            "Alle børnene spillede ishockey, undtagen inuk, han var puk!",
            "Alle børnene løb ud af den brændende skole, undtagen Klavs mongol, der var en, der havde solgt hans rullestol.",
            "Alle børnene kiggede ned i dybfryseren, undtagen Thue, han havde ligget der i en uge!",
            "Alle børnene var fattige, undtagen Frode, Han kunne sin fars pinkode.",
            "Alle børnene kom hele ud af krokodillefarmen, undtagen Finn, Bo og Asger, de kom ud som skind, sko og tasker!",
            "Alle børnene fodrede hunden, undtagen Arne, det var hans arme.",
            "Alle børnene talte pænt, undtagen Volmer, han var bornholmer.",
            "Alle børnene røg hash, undtagen nellynot, hun røg pot",
            "Alle børnene kom sikkert hjem fra børnehaven, undtagen Thor, han blev ramt af et meteor.",
            "Alle børnene kom ud fra sodavandsfabrikken, undtagen Anne, hun kom ud på kande.",
            "Alle børnene løb væk fra giftgassen, undtagen Åge, han troede det var tåge.",
            "Alle børnene havde sexualundervisning, undtagen Grethe, det var hendes ben, de spredte...",
            "Alle børnene dyrkede oralsex, undtagen Jønke, det var ham, der skulle synke.",
            "Alle børnene brækkede sig ned i brønden, udentagen Bitten, hun sad nede i den.",
            "Alle børnene undgik krigen, undtagen Emil, han blev ramt af et missil!",
            "Alle børnene tissede, undentagen Lotte, for hun var potte.",
            "Alle børnene løb fra den grumme rocker, undtagen Kalle, han fik en skalle.",
            "Alle børnene stod i vand til halsen, undtagen Mille, hun var for lille.",
            "Alle børnene gik ud af bussen, undtagen Jesper, han var spændt efter!",
            "Alle børnene tog glade hjem fra påskeferien, undtagen Ole og hans far, de var om bord i Scandinavian Star.",
            "Alle børnene løb ud af den brændene skole, undtagen Artige Finn, for det ringede jo ind!",
            "Alle børnene løb da telefon-boksen sprang i luften, undtagen Inge, - hun var ved at ringe!",
            "Alle børnene kom over vejen, undtagen Rolf, han blev ramt af en Golf!",
            "Alle børnene løb ud af den brændende skole, undtagen Mohammed, han var spastisk lammet!",
            "Alle børnene sad på betonklodsen, undtagen Gunner, han lå under.",
            "Alle børnene havde vinden i ryggen, undtagen Max, han havde en saks.",
            "Alle børnene sad rundt om lejrbålet, undtagen Bent, det var ham, der var tændt.",
            "Alle børnene lugtede til blomsterne, undtagen Mads, han sniffede lightergas.",
            "Alle børnene tog Easy Line, undtagen Jannick, han tog Titanic.",
            "Alle børnene spillede bordtennis, undtagen Bøje, det var hans øje.",
            "Alle børnene spiste medisterpølse, undtagen Bjarne, Det var hans tarme.",
            "Alle børnene sang, undtagen Ruben, han havde kræft i struben.",
            "Alle børnene havde pæne tekstikler, undtagen Rolf, hans far spillede golf.",
            "Alle børnene tegnede på tavlen, undtagen Grit, for hun var kridt.",
            "Alle børnene var glade, undtagen Kurt, for ham var livet surt.",
            "Alle børnene bollede med læreren, undtagen Ellen, hun bollede med pedellen.",
            "Alle børnene brændte inde, undtagen Søren, det var ham der havde låst døren",
            "Alle børnene drak rød sodavand, undtagen Britt, hun drak sprit.",
            "Alle børnene fik forevist den store kødhakkemaskine, undtagen Lars, han blev til fars.",
            "Alle børnene hoppede fint over pigtrådshegnet, undtagen Ronnie, nu hedder han Connie",
            "Alle børnene hørte brandalarmen, undtagen kent, han havde ikke sit høreapperat tændt.",
            "Alle børnene legede krig, undtagen Sussi, hun havde ingen uzi",
            "Alle børnene spiste hestebøffer, undtagen Ronny, det var hans pony ",
            "Alle børnene kiggede på det gabende hul, undtagen Hanne, det var hendes pande ",
            "Alle børnene legede med tændstikker, undtagen Winnie, hende gik der ild i.",
            "Alle børnene blev kørt til skole, undtagen Oda, hendes far havde en Skoda. ",
            "Alle børnene fik julegaver, undtagen Emil, Han skulle alligevel dø til april. ",
            "Alle børnene har en computer der virker - undtagen Harry, han har en Atari. ",
            "Alle børnene løb væk fra bomben, undtagen Britt, hun havde defusekit",
            "Alle børnene kastede med håndgranater, undtagen Preben, det var ham der greb dem.",
            "Alle børnene lavede frikadeller, undtagen Lars, han var fars. ",
            "Alle børnene legede atomfysikere, undtagen Valde, det var ham de skulle spalte. ",
            "Alle børnene legede på vejen, undtagen Per, han leger ikke mer'. ",
            "Alle børnene manglede penge, undtagen Keld, han printede dem selv.",
            "Alle børnene nippede til urin-prøven, undtagen Gunnar, han tog en bunder. ",
            "Alle børnene solgte limonade, undtagen Jack, han solgte crack. ",
            "Alle børnene stod ved komfuret, undtagen Rasmus han sad på et gasblus. ",
            "Alle børnene havde normal sex, undtagen Janus, han ville hellere ha' den op i Anus. ",
            "Alle børnene fik ros af læreren, undtagen Palle, han fik en skalle.",
            "Alle børnene havde sexualundervisning, undtagen Grethe, det var hendes ben de spredte.",
            "Alle børnene legede læge, undtagen Peter, han var termometer.",
            "Alle børnene kunne lege, undtagen Finn, han havde muskelsvind.",
            "Alle børnene spiste frikadeller, undtagen Rikke Larsen, hun havde skidt i farsen!",
            "Alle børnene var glade da 2. verdenskrig sluttede, undtagen Hitler, han mistede sine titler.",
            "Alle børnene kom ud af junglen, undtagen Camilla, hun blev voldtaget af en gorilla.",
            "Alle børnene måtte prostituere sig, undtagen Otto, han havde vundet i Lotto.",
            "Alle børnene røg, undtagen Gunner, han havde ingen lunger",
            "Alle børnene havde tilfredse forældre, undtagen Morten, han var født før aborten.",
            "En far siger til sønnen: Nu kommer storken snart med din lillesøster. Sønnen svarer - du er da en idiot. Her vrimler byen med fisse og så knepper du storken !!",
            "Hvad får man hvis man stopper 27 trekantede advarselsskilte ned i en neger? Verdens største toblerone!",
            "Hvordan forvandler man en sild til en haj? man gifter sig med hende.",
            "Jeg har det med kvinder som med elefanter: Jeg kan li' at kigge på dem men vil ikke eje en.",
            "Hvorfor har unge italienske mænd skæg? De vil så gerne ligne deres mor.",
            "En kvinde siger noget klogt, når hun starter med: \"En mand fortalte mig engang...\"",
            "Ja, det er jo sådan at: Gud skabte mennesket, derefter skabte han kvinden...",
            "Spåkonen til frøen... - \"Du vil møde en super dejlig pige, som vil vide alt om dig.\" - \"Fedt nok... møder jeg hende til en fest eller sådan noget?\" -\"Nej, du møder hende i en biologitime til næste sommer.\"  ",
            "Hvad gør en hveps der har problemer med at finde noget at lave? Den går på bistand!",
            "Hvad kalder man det kvindelige kønsorgan på et pindsvind? En stikdåse..",
            "Hvad er forskellen på en myg og en lærer? myggen irriterer kun om sommeren.",
            "Den ene gås til den anden: Tror du på liv efter juleaften? ",
            "Hvordan ved man, at to elefanter har dyrket sex i din baghave? Affaldsposen er væk!",
            "Hvad er ligheden mellem en bokser og en bøsse ? De får begge tæsk i ringen",
            "Hvorfor har en isterning ikke arme og ben? Fordi den er vandskabt",
            "Det var Osama jr. der kom hjem fra skole med 03 i historie! Far? jeg har fået 03 i historie. kom til at sige at eiffeltårnet er højre end wtc! Osama: Jamen knægt. den ordner far lige!",
            "Det var en indvandrer der havde kneppet en dansk Blondine, Han havde smittet hende. Så inde i retsalen så spørger dommeren så, hvorfor sagde du ikke du havde HIV? Det sagde jeg også: \"HIV i den, HIV i den, HIV i den...\"",
            "Knægten til sin farmand; Jeg har kneppet farmor. Farmand: Du har vel for fanden ikke kneppet farmor?! Knægten: Knepper du min mor, knepper jeg din...",
            "Lille Lise går ude på gaden og pludselig kommer en man og river hendes bukser ned, men Lille Lise griner bare fordi hun ved at den mand ikke kan passe hendes bukser.",
            "Lille Lise sidder i biografen og pludselig begynder manden ved siden af, at rave hende på skødet men Lille Lise griner bare fordi hun ved godt, at slikket ligger i den anden lomme. ",
            "Lille Peter var i bad med sin far, lille Peter siger: Hva er det for en diller frederik der hænger der? hvorfor pejer den ned? Far: det er pga jordens tiltræknings kraft! Peter: Hvordan kan det så være at sidst du var i bad med mor peget den op ad? Far: det er fordi mor har jord i hoved",
            "Hvorfor er invandrere så dårlige til fodbold? Fordi hver gang de får et hjørne åbner de en Kiosk",
            "En mor lavede pandekager til sine to sønner på 3 og 5 år. Børnene begyndte at skændes om hvem der skulle have den første pandekage og moderen så chancen for at give børnene en lille moralsk lektion: \"Hvis Jesus havde siddet ved dette bord havde han sagt: \"Lad min broder få den første pandekage - jeg selv kan vente.\" Den ene bror kiggede på den anden og sagde: \"Ok...Per...du kan være Jesus.\"",
            "Hvorfor har kvinder ben ? - Ellers ville de have et slimspor efter sig !",
            "En dansker og en englænder var ude at sejle. Da de kom ud på havet begyndte båden at vippe, og så faldt danskeren i vandet. Han råbte: \"HJÆLP!\", og så sagde englænderen: \"what?\", og derefter sagde danskeren: \"Ja gu' fanden er det våt!\"",
            "Hvad er forskellen mellem en blondine og en tallerknen? En tallerknen kan kun knaldes en gang.",
            "Bonden har 3 køer Rie, Fie og Mie der hver fik en kalv. Rie`s kom til at hedde Risse. Mie`s Misse. Hva hedder Fie`s kalv?",
            "Hvis en kylling brækker et ben, går den så med æggestokke?",
            "Hvad laver 1000 blondiner på bunden af havet? De leder efter Leonardo Di Caprio! ",
            "Hvad har en klog blondine og en UFO tilfælles? Man hører hele tiden om dem, men ser aldrig en.",
            "Hvorfor bliver blondiner begravet i trekantede kister? Fordi de spreder benene når det bliver mørkt!",
            "Hvordan kan man kende forskel på en blondine og en Lolitadukke? Blondinen har mobiltelefon!",
            "Hvad kalder man en blondine på et universitet? En gæst.",
            "Hvad sker der hvis en dansk blondine flytter til Sverige? Intelligensen stiger i begge lande.",
            "Hvad er fordelen ved at have en blondine med i bilen? Så må man holde på handikapparkering!",
            "Hvorfor blev blondinen skuffet, da hun kom til London? Hun opdagede at Big-Ben var et ur!",
            "En blondine sad lidt nedtrykt på politi stationen... \"-Jeg blev voldtaget af en idiot\" græd hun. \"-Hvordan vidste du det var en idiot?\" spurgte betjenten. \"-Jeg blev nødt til at hjælpe ham!\" svarede blondinen.",
            "Blondinen blev spurgt om sin fødselsdato. \"-Det er den 23 Juli\", \"-Hvilket år?\", \"-Det er da hvert år!\"",
            "Hvad er det første en blondine gør når hun vågner? Tager tøj på og går hjem.",
            "Hvad er forskellen mellem den afskyelige snemand og en klog blondine? Den afskyelige snemand er blevet set.",
            "Hvad er de tre sværste år i et Blondine's liv? 1. klasse!",
            "Hvorfor skifter blondinen kun sin babys ble en gang om måneden? Der står 10 kg på pakken.",
            "Hvad er ligheden mellem en blondine og et jagtgevær? De skal begge knækkes på midten og lades bagfra.",
            "Hvad er forskellen på en blondinehjerne og AIDS? AIDS udvikler sig.",
            "Hvorfor døde blondinen, da hun drak mælk? Koen faldt ned over hende.",
            "Hvad svarer en blondine på spørgsmålet: \"Er du seksuelt aktiv?\" Nej, jeg ligger der bare.",
            "Hvad er en blondines opfattelse af sikker sex? At låse bildøren.",
            "Hvad sagde blondinens højre ben til det venstre? Ved det ikke, De er aldrig sammen.",
            "Hvorfor bliver en blondine aldrig søsyg? Hun er vant til søgang fra vandsengen.",
            "Hvorfor brækkede blondinen benet, da hun samlede blade sammen? Hun faldt ned fra træet.",
            "Hvorfor kørte blondinen 50 gange rundt om blokken? Blinklyset havde sat sig fast",
            "Hvorfor foretrækker blondiner biler med soltag? Der er bedre plads til benene.",
            "Hvorfor var blondinen stolt af at have gennemført sit puslespil på 6 måneder? Der stod \"2 til 4 år\" på pakken!",
            "Hvorfor spiser blondiner ikke pulver-suppe? De kan ikke finde ud af at få vand ned i de små poser!",
            "Hvad siger man til en blondine, der ikke vil gå med en hjem? Tag en øl mere...",
            "Hvad siger en blondine, der er på toppen af sin karriere? \"Velkommen til McDonalds!\"",
            "Hvorfor kan blondiner ikke få kogalskab? Fordi det er en hjernesygdom!",
            "Hvad siger blondiner efter sex? Næste!",
            "Hvad er ligheden på en blondine og en palme? De er begge interesante, når de har store nødder.",
            "Hvad er blondiners parringshyl? Guud, hvor er jeg fuld!",
            "Hvad er ligheden mellem en blondine og en colaflaske? De er begge tomme fra halsen og opefter!",
            "Hvad er ligheden mellem en blondine og en elektrisk standerlampe? De kan begge tændes med en pegefinger!",
            "Hvad er forskellen mellem en blondine og en lygtepæl? Hos en lygtepæl lyser pæren.",
            "Hvordan ved man, at en blondine er liderlig? Når man stikker hånden ned i hendes trusser, føles det som en hest, der gumler havre.",
            "Hvad er ligheden mellem en blondine og en tallerken? Først knalder du den, og så smider du den ud.",
            "Hvorfor går blondiner altid i så stramme nededele? For at holde lårene sammen.",
            "Hvorfor er blondinen så dårlig til brystsvømning? Når hun bliver våd mellem benene, vender hun sig om på ryggen",
            "Hvad er ligheden på en blondine og en motervej? De bliver begge slidt op af gummi.",
            "Hvad er ligheden mellem en ovn og en blondine? Man skal varme begge dele op inden man smider kødet ind.",
            "Hvad er ligheden mellem blondiner og høns? Hver aften hopper de op på pinden og gokker.",
            "Hvad er forskellen på en blondine og en bowlingkugle? Der kan kun være 3 fingre i en bowlingkugle!",
            "Hvad er ligheden mellem en blondine og en bowlingkugle? Begge to har 3 huller, som rigtig mange mænd har haft fingrene oppe i, fordi de har betalt for en halv time.",
            "Hvad er forskellen på en blondine og en myg? - En myg holder selv op med suge, når den har fået nok!",
            "Hvad sagde Blondinen da hun kom ud efter en IQ-test? - \"Yes! Jeg fik 13!\"",
            "Hvorfor har blondiner gennemsigtige madkasser? - Ellers kan de ikke se om de er på vej til eller fra arbejde.",
            "Hvorfor kan blondiner ikke lave isterninger? - Fordi de altid glemmer opskriften",
            "Hvordan får man en enarmet blondine ned fra en lygtepæl? - Man vinker til hende.",
            "Hvad er ligheden mellem en støvsuger og en blondine? - Når sugeevnen falder, så skal sækken skiftes ud.",
            "Din mor er så gammel, at dengang hun gik i skole, var der ikke noget der hed Historie",
            "Din mor er så fed, at hvis hun faldt i et Øresund ville Jylland blive oversvømmet",
            "Din mor er så fed, at hendes blodtype er Nutella",
            "Din mor er så fed, at hvis hun tager et blåt lagen på ligner hun atlanterhavet.",
            "Din mor er så fed, at når hun er i biografen, sidder hun ved siden af alle.",
            "Din mor er så fed, at hun kan sælge skygge i ørkenen.",
            "Din mor har så store ører, at selv DUMBO vil grine.",
            "Din mor er så dum, at det mest intelligente der nogensinde er kommet ud af hendes mund er min pik!",
            "Din mor er så fed, at hun har sit eget postnummer.",
            "Din mor er så fed, at hun køber tamponer i tæppeland",
            "Din mor er så fed, at elevatoren kun vil køre hende nedad",
            "Din mor er så fed, at når hun går forbi fjernsynet, mister du fem minutter af programmet.",
            "Din mor er så fed, at hun kan kickstarte en færge.",
            "Din mor er så fed, at hun ikke kan se jorden i en radius af 20 meter.",
            "Din mor er så fed, at når man vil kneppe hende, skal man slå hende på låret og ride ind på bølgen.",
            "Din mor er så grim, at hun må gemme sig i jagt sæsonen.",
            "Din mor er så fed, at hun kunne stoppe hungersnøden i Afrika ved en fedtsugning.",
            "Din mor er så fed, at hvis hun har en grøn bluse på, så kommer folk og vil smide deres gamle glas og flasker i hende",
            "Din mor er så fed, at når hun ligger på stranden, så kommer Green Peace og skubber hende i vandet igen.",
            "Din mor er så fed, at hun blev døbt i Lalandia.",
            "Din mor er højest, når hun ligger ned",
            "Din mor er så fed, at hvis hun sætter sig ind i en monstertruck, bliver det til en lowrider.",
            "Din mor er så fed, at da jeg prøvede at køre uden om hende, løb jeg tør for benzin.",
            "Din mor er så fed, at hvis hun går med højhælede sko, kan hun finde olie.",
            "Din mor er så fed, at badevægten viser -|-|-|-",
            "Din mor er så fed, at ikke engang Bill Gates har råd til at give hende en fedtsugning.",
            "Du har spillet for meget computer når: du kigger på solen, og tænker du på hvad opløsning den er i.",
            "Du har spillet for meget computer når: du kan få et fult måltid ud af krummerne i keyboardet. ",
            "Du har spillet for meget computer når: der er en skygge bag skærmen, også når du ikke sidder der. ",
            "Du har spillet for meget computer når: du kan forsvare basen uden skærmen er tændt. ",
            "Du har spillet for meget computer når: du lukker øjnene og ser et crosshair. ",
            "Du har spillet for meget computer når: du ser TV avis og prøver at trække en boks rundt om soldaterne på skærmen for at flytte dem. ",
            "Du har spillet for meget computer når: du slukker for bilen og leder efter quicksave knappen for at kunne starte samme sted næste gang. ",
            "Du har spillet for meget computer når: chefen tager dig i at sove på kontoret og du skriger \"Admin... Wallhack\". ",
            "Du har spillet for meget computer når: du tror at 1. Verdenskrig var mellem GDI og NOD og at 2. Verdenskrig var mellem Terran, Zerg og Protoss. ",
            "Du har spillet for meget computer når: din kæreste hedder Lula og bor i nederste skuffe. ",
            "Du har spillet for meget computer når: du skyder din klasselærer da du tror vedkommende er en dæmon (hvilket også kan ske). ",
            "Du har spillet for meget computer når: du undrer dig over hvorfor der ikke står minimumskrav på din læsebog. ",
            "Du har spillet for meget computer når: du tænker på at lade din søn arve din DiabloII æske. ",
            "Du har spillet for meget computer når: du råber cheater hver gang du ser en blive dræbt i en film. ",
            "Du har spillet for meget computer når: du arbejder på en opgave og din hjerne går kold, og så leder du efter reset-knappen. ",
            "Du har spillet for meget computer når: du spiser blomsterne i form af at de er en lækker tilberedt tallerken der står ensomt i gangene i RTCW. ",
            "Du har spillet for meget computer når: du hysterisk siger at musefælder burde være forbudt. ",
            "Du har spillet for meget computer når: du frier til dit tastatur. ",
            "Du har spillet for meget computer når: du ikke kan finde tændsluk-knappen, til dit vindue. ",
            "Du har spillet for meget computer når: du automatisk kigger efter snipere når du en sjælden gang går udenfor. ",
            "Du har spillet for meget computer når: du kan genkende en eller flere af disse \"Du har spillet for meget computer når...\" ",
            "Du HaR SpIlLeT fOr MeGeT cOmPuTeR nÅr: Du BeGyNdEr At SkRiVe DiN StIl ElLeR AnSøGnInG SåDaN HeR. ",
            "Du har spillet for meget computer når: du siger haha jeg skød dig gennem muren efter samleje. ",
            "Du har spillet for meget computer når: du kigger dig hurtigt til højre og venstre når du skal forbi et hjørne. ",
            "Du har spillet for meget computer når: dine øjne gør ondt i dagslys. ",
            "Du har spillet for meget computer når: du siger lol, rofl, *IRL*.",
            "Du har spillet for meget computer når: du kalder folk n00b hvis de ik' kan deres tabel. ",
            "Du har spillet for meget computer når: du står og leder efter tasten til buymenu når du træder ind i den lokale kiosk. ",
            "Du har spillet for meget computer når: et døgn i sommerferien er 30 timer.",
            "Du har spillet for meget computer når: du dukker dig hver gang du bliver nervøs. ",
            "Du har spillet for meget computer når: en babe spørger efter dit nummer, og hun får dit steamID. ",
            "Du har spillet for meget computer når: du bliver stoppet, og spørger politimanden om du må se hans stats. ",
            "Du har spillet for meget computer når: du hopper som en idiot, når du går rundt udenfor. ",
            "Du har spillet for meget computer når: du har en \"Will work for Bandwidth\" T-shirt. ",
            "Du har spillet for meget computer når: brian-terningerne i din bil er erstattet af en afbrændt CPU. ",
            "Du har spillet for meget computer når: du giver lægen dit ICQ# i stedet for personnummer. ",
            "Du har spillet for meget computer når: du aldrig flytter, da ejendomsmæglerne ikke har \"båndbredde\" under info på nye huse.  ",
            "Du har spillet for meget computer når: din familie logger på IRC for at snakke med dig. ",
            "Du har spillet for meget computer når: det første dit barn lærer at sige er \"GO GO GO\". ",
            "Du har spillet for meget computer når: du synes gameplayet i verden generelt er for langsomt. ",
            "Du har spillet for meget computer når: du anser din nabo for at være terrorist. ",
            "Du har spillet for meget computer når: din ide om \"ferie\" er at tage til eksotiske steder.. og spille PC. ",
            "Du har spillet for meget computer når: du aftjener værnepligt og din s'jant bliver skide sur fordi du skifter magasin hver gang du har løsnet 5 skud. ",
            "Du har spillet for meget computer når: du i idræt tager du en kniv frem for at løbe hurtigere. ",
            "Du har spillet for meget computer når: du går sidelæns om hjørner. ",
            "Du har spillet for meget computer når: du i skolen kalder læreren for en spammer når han prøver at lære dig noget. ",
            "Du har spillet for meget computer når: du begynder at snakke til din PC. ",
            "Du har spillet for meget computer når: du bliver deprimeret hver gang en NPC dør. ",
            "Du har spillet for meget computer når: du kan huske alle cfg's i alle spil du har spillet men kan stadig ikke huske dit telefon nr. ",
            "Du har spillet for meget computer når: du bliver ved med at stille folk det samme spørgsmål indtil de svarer det samme hver gang, for at være sikker på at du ikke går glip af vigtige oplysninger. ",
            "Du har spillet for meget computer når: når du spiller CS og du sidder og læner dig til siden når du vil kigge om der er noget omkring et hjørne. ",
            "Du har spillet for meget computer når: du kan grine af jokes der handler om spil. ",
            "Du har spillet for meget computer når: du synes at Benders CS tegneserier er sjove.",
            "Du har spillet for meget computer når: du har et spillager svarende til en rollespillers forbrug af mascare",
            "Du har spillet for meget computer når: du har forsøgt at forklare dine venner hvordan man skriver 1337.",
            "Du har spillet for meget computer når: du har en lang og interrasant historie bag dit nick. ",
            "Du har spillet for meget computer når: du glæder dig til at skærmen med indbygget solarie bliver opfundet. ",
            "Du har spillet for meget computer når: du ser kun nyhederne af den grund at der skulle komme noget om en dansk spiludvikler. ",
            "Du har spillet for meget computer når: du prøver at rocketjumpe. ",
            "Du har spillet for meget computer når: du hører stemmer som siger \"Fire in the hole\" og \"Affirmative\" ",
            "Du har spillet for meget computer når: du drømmer om Terrorister og Counterterrorister. ",
            "Du har spillet for meget computer når: du ikke kan forstå hvorfor politibetjentene fra film ikke kan bunnyjumpe.",
            "Du har spillet for meget computer når: du sidder oppe 24/7/365 ",
            "Du har spillet for meget computer når: din hud ikke kan tåle sollys. ",
            "Du har spillet for meget computer når: du kalder din arbejdsgiver for CL ",
            "Du har spillet for meget computer når: du trykker på \"use-knappen\" når du ser en person i en kittel ",
            "Du har spillet for meget computer når: du bruger mere tid på at spille cs på as_oilrig end på lektier.",
            "Du har spillet for meget computer når: DU redder rengøringsdamen fra det farlige lokum i det der skulle være en bombe i det ",
            "Du har spillet for meget computer når: der ligger gammelt mad og cola fra 1998 ",
            "Du har spillet for meget computer når: du har en uges opvask stående foran skærmen, men det dækker ikke for den, og musen er der masser af plads til, oven på pizzaæsken. ",
            "Du har spillet for meget computer når: du er fan af en klan.",
            "Du har spillet for meget computer når: det er vigtigt for dig at dit kabinet ser godt ud inden i. ",
            "Du har spillet for meget computer når: du er stamkunde hos den lokale Colapusher. ",
            "Du har spillet for meget computer når: du ikke længere bruger kommandoen \"sit\" til din hund, men: \"hold this position\"",
            "Du har spillet for meget computer når: du har XplayN eller andet spilsite som startside",
            "Du har spillet for meget computer når: du ikke kan forstå hvorfor hovedpersonen i gyserfilm ikke bruger quicksave konstant",
            "Du har spillet for meget computer når: du sidder og skriger TEAMS! når der er nyheder om USA og Irak",
            "Du har spillet for meget computer når: du har sat gamle mørklægningsgardiner for vinduerne, fordi solen skinnede på skærmen gennem dine gamle gardiner. ",
            "Du har spillet for meget computer når: du forsøger at tjekke Rambos stats. ",
            "Du har spillet for meget computer når: du er overbevist om at Rambofilmene foregår i \"easy mode\". ",
            "Du har spillet for meget computer når: du kan lave en tegning at et tastatur hvor alle tasterne sidder de rigtige steder. ",
            "Du har spillet for meget computer når: du er afhænging af Cola/kaffe. ",
            "Du har spillet for meget computer når: du begynder at lagge lige så snart 10 mennesker står samlet.",
            "Du har spillet for meget computer når: du klager til den Internationale Menneskerettighedsdomstol over at du ikke kan få bredbånd101. ",
            "Du har spillet for meget computer når: du tror at AIDS at en form for bredbånd. ",
            "Du har spillet for meget computer når: du tager en laptop med på overlevelsestur. ",
            "Du har spillet for meget computer når: din lærer deaktivererer din chatfunktion i timerne. ",
            "Du har spillet for meget computer når: du opfatter ordet nørd som kompliment. ",
            "Du har spillet for meget computer når: du ikke kan forstå at man ikke kan blive cand. nørd. ",
            "Du har spillet for meget computer når: du ikke længere vil være kristen, da du mener at Counter-Strike er en meget bedre relgion! ",
            "Du har spillet for meget computer når: du læser spil manualen som godnatlæsning! ",
            "Du har spillet for meget computer når: du betegner køerne på motorvejene som lag. ",
            "Du har spillet for meget computer når: du pisker gennem Netto, for at handle da du kun har 5 sekunders buytime... ",
            "Du har spillet for meget computer når: din lærer fortæller dig noget du ved i forvejen, kalder du ham for Lamer ",
            "Du har spillet for meget computer når: du vil ringe til en ven IRL, tager du dig selv i at diale hans IP. ",
            "Du har spillet for meget computer når: du ikke kan svare på hvad årstal vi har, men til gengæld kan svare på hvad den præcise URL er til den side hvor dine stats står på.. ",
            "Du har spillet for meget computer når: dit sexliv ender på .dk",
            "Du har spillet for meget computer når: nogen spørger dig om noget, og du ikke ved det, så svarer du fek.s prøv at klikke ind på www.smålandesbruttonationalprodukt.dk ",
            "Du har spillet for meget computer når: man ser en fluesvamp, og tror at man vokser til dobbelt størrelse. ",
            "Du har spillet for meget computer når: man har én ven ... google",
            "Du har spillet for meget computer når: du spiser og er imponeret over hvor god en gaffel er som controller. ",
            "Du har spillet for meget computer når: du tror at grimme folk bare har en lavere opløsning end andre. ",
            "Du har spillet for meget computer når: du syntes at detaljegraden på græs er for lav. ",
            "Du har spillet for meget computer når: du kalder folk ved deres nickname. ",
            "Du har spillet for meget computer når: du omtaler levende folk som \"live\". ",
            "Du har spillet for meget computer når: du omtaler timer som \"realtime\". ",
            "Du har spillet for meget computer når: du ser en Securitas-vagt i en butik, og råber \"Camper!!! Camper!!!\"",
            "Du har spillet for meget computer når: du begynder at betale vægt-afgift på dine øjenlåg...",
            "Du har spillet for meget computer når: din indkøbs-liste består af ting som.: SIG Commando, Prim. Ammo, Kevlar + Helmet og Dual Berettas.... ",
            "Du har spillet for meget computer når: du prioiterer alt andet et CS som sekundært... ",
            "Du har spillet for meget computer når: du er syg, råber du konstant \"Medic!!! Medic!!\"... ",
            "Du har spillet for meget computer når: du er forlovet med din Diablo ll emballage... ",
            "Du har spillet for meget computer når: du døber dit barn Gordon Freeman...¨ ",
            "Du har spillet for meget computer når: du ser en film og der er en der sniper og du råber \"AWP LUJER\" ",
            "Du har spillet for meget computer når: du mener du kan ændre dit frikvaters længde ved at skrive mp_buytime 999999999999999 på tavlen! ",
            "Du har spillet for meget computer når: Shadowman indgår hyppigt i dine drømme. ",
            "Du har spillet for meget computer når: du forsøger at forklare dine forældre at du har fået virus, og derfor ikke kan komme i skole før du har fået den fjernet. ",
            "Du har spillet for meget computer når: du ved mere om Linux end dit pensum i Tysk.",
            "Du har spillet for meget computer når: du ser nogle mennesker der står stille, og straks leder efter tasten 'E' for at redde dem.",
            "Du har spillet for meget computer når: du er på arbejde og omtaler du nyansatte som n00bies ",
            "Du har spillet for meget computer når: dine bedsteforældre snakker for lavt leder du efter volumecontrollen for at skrue op ",
            "Du har spillet for meget computer når: du er fuld og leder efter degauss-knappen ",
            "Du har spillet for meget computer når: du tror at du kan være manager for Arsenal og det danske Landshold. ",
            "Du har spillet for meget computer når: du er på boomtown's site og venter på en ny nyhed for at få 1. comment.",
            "Du har spillet for meget computer når: du ikke ved der findes andre retter end cola og pizza ",
            "Du har spillet for meget computer når: du tror at H.C Andersen var ham der opfandt pizzaen ",
            "Du har spillet for meget computer når: din mor beder dig om at rydde op og du så fjerner alt overflødigt fra din hardisk ",
            "Du har spillet for meget computer når: du tror at \"all your base are belong to us\" er korrekt engelsk ",
            "Du har spillet for meget computer når: du undrer dig over hvor lyddæmperen til din gaffel er blevet af ",
            "Du har spillet for meget computer når: du tror at du er Yuri og forgæves prøver at styre din skildpadde i dit akvarie.. ",
            "Du har spillet for meget computer når: du tror du kan trykke \"tilbage\" når du har gjort en fejl *IRL* ",
            "Du har spillet for meget computer når: du synes det er mærkelig du larmer når du går ",
            "Du har spillet for meget computer når: din familie kun er pc-interesseret",
            "Du har spillet for meget computer når: du ved mere end din fætter som er IT-Ingeniør ",
            "Du har spillet for meget computer når: du bliver ved med at chatte med dine venner selv efter at du er død. ",
            "Du har spillet for meget computer når: du tror skolen er en tutorial til livets spil. ",
            "Du har spillet for meget computer når: du ser et dyr og siger; \"fed .gif\" ",
            "Du har spillet for meget computer når: din mor siger du skal hjælpe og du siger; \" Need Back Up, Taking Fire\" ",
            "Du har spillet for meget computer når: din lærer kommer ind i lokalet og du siger: \"Enemy spotted\" ",
            "Du har spillet for meget computer når: du så endeligt får ramt din lærer i synet med et stykke viskelæder og du siger: \"Enemy down\"!, mens de andre i klassen råber: Lo2 headshot!! ",
            "Du har spillet for meget computer når: kvinden vil have dig med i seng og du siger \"Regroup Team\" ",
            "Du har spillet for meget computer når: du er i krig og du løber tør for ammo og du prøver at få \"Console\" frem for at skrive \"Give All\" ",
            "Du har spillet for meget computer når: du råber area clear hver gang du går ind i et tomt rum. ",
            "Du har spillet for meget computer når: du tror at skimasker kun er forbeholdt terrorister. ",
            "Du har spillet for meget computer når: du tror at blåt tøj med maske er moderigtigt. ",
            "Du har spillet for meget computer når: du taber i et kortspil og brokker dig pga. lav fps og ping.",
            "Du har spillet for meget computer når: manden på net-cafén kender dig bedre end din egen mor. ",
            "Du har spillet for meget computer når: du har dine initialer på din PRIVATE stol på den nærmeste net-cafe. ",
            "Du har spillet for meget computer når: din computer har flere MHz end din bank-konto har kr. ",
            "Du har spillet for meget computer når: du kender prisen på din drømme gaming maskine. ",
            "Du har spillet for meget computer når: din kæreste logger på IRC for at spørge dine klan m8s hvad du laver.",
            "Du har spillet for meget computer når: du undrer dig over at Fakta siger at 5 minutter er kort tid, når du kan nå at handle ind på 5 sek. ",
            "Du har spillet for meget computer når: der på samtlige af dine stile står dit nickname istedet for navn.",
            "Du har spillet for meget computer når: du har solgt din mobiltelefon efter du fik installeret Skype.",
            "Du har spillet for meget computer når: du ser mere frem til det næste CPL event istedet for VM i fodbold.",
            "Du har spillet for meget computer når: du glæder dig mere til det næste LAN end familieturen til et flot sommerhus.",
            "Du har spillet for meget computer når: du er bange for at gå i bad med mistanken om at din nabo bruger wallhack.",
            "Det danske Postvæsen overvejde, at lave en frimærkeserie med FCK-spillere, men droppede dog ideen, da det var misvisende overfor afsenderen, hvilken side der skulle spyttes på.",
            "Den eneste positive ting ved en FCK-fan, er resultatet af hans HIV-test.",
            "\"Telefonen ringer i Lyngby's klubhus: - Hvornår spilles kampen i morgen, spørger manden i telefonen. Til det svarer L.F.C.-lederen, - Hvad tid kan du komme???",
    };
}

